### ISSUE TITLE
TodoItem belongs to user

### ISSUE THREAD

**Issue by Raileanv** [Raileanv/todo_anarchy#18]
Lets add scenario: 
As a user I can create todo_items and can edit created by me todo_items. And I can not edit todo items added by other users

- [x] add to `todo_item` new field user_id which will store id of a creator
- [x] make TodoItem belongs_to user and User has_many :todo_items 
- [x] in show page show edit button only for owner of todo_item
- [x] in the todo_item controller add a verification before save, that current_user is an owner of todo_item and only if yes allow to save

**Comment by ziGihouse** [comment]
One head are good
two better
